### ISSUE TITLE
Add affinity of a card 

### ISSUE THREAD

**Issue by ikke2902** [fiki574/Skylords-Reborn-API-UI#1]
New to GitHub, not sure if this format is fine.

I'd like to see affinity being added to the card ID here
https://github.com/fiki574/Skylords-Reborn-API-UI/tree/master/Auctions#get-apicardscardid

or

being added along with the auction
https://github.com/fiki574/Skylords-Reborn-API-UI/tree/master/Auctions#get-apicardscardid

This was mentioned on the forum here
https://forum.skylords.eu/index.php?/topic/7150-skylords-reborn-api/&do=findComment&comment=88876

**Comment by fiki574** [comment]
It is planned addition, however not a priority. Leaving this opened for future implementation.
