### ISSUE TITLE
Auction Sorting by auctionId

### ISSUE THREAD

**Issue by NovacX** [fiki574/Skylords-Reborn-API-UI#12]
**Suggestion**
I strongly suggest changing the /api/auctions/:page/:number endpoint to sorting by auctionId. 

**Usecase and issue Description:**
I frequently download the latest csv full export to get an update on the history of card prices. As the csv export is only updating every 20 minutes, I try to retrieve the latest auctions by using the /api/auctions/:page/:number endpoint (which is updating every 10 minutes). But as it is not sorted by auctionId, it is not enough to only download the highest or lowest X pages. Instead I would have to download all pages, due to the price sorting.

**Reason**
For regular use cases like realtime frontends for the API, this has no performance or quality effect. But for applications using historical or large scaled data, this leads to much lower amounts of server-side requests, while making the data more up-to-date in the application.

**Comment by fiki574** [comment]
Maybe corelated with this issue: https://github.com/fiki574/Skylords-Reborn-API-UI/issues/6

It could possibly be an additional sorting option, just as some are suggested in the mentioned issue.

**Comment by fiki574** [comment]
Implemented as a part of the new Skylords Reborn API Hub: https://hub.backend.skylords.eu/api/docs/auctions/#/Advanced/get_api_auctions_advanced
