### ISSUE TITLE
Zipping on /api/auctions/export

### ISSUE THREAD

**Issue by NovacX** [fiki574/Skylords-Reborn-API-UI#13]
**Suggestion**
Add file zipping for csv endpoint and update it more frequently. Recommending JSZip, depending on the server-side implementation.

**Reason**
Comparing the raw csv data to an archive, a download currently has around 2 Mb for each request on the export. Instead zipping it with level 9 compression brings it down to around 100 kb. It neither has a large impact on the client, nor server application, but significantly reduces internet usage on a large scale. 

In the end, this should also bring you to increasing server-side performance, which might lead you to decreasing the csv export update interval to 10 minutes or even 5 minutes.

**Comment by NovacX** [comment]
> 
> 
> **Suggestion**
> Add file zipping for csv endpoint and update it more frequently. Recommending JSZip, depending on the server-side implementation.
> 
> **Reason**
> Comparing the raw csv data to an archive, a download currently has around 2 Mb for each request on the export. Instead zipping it with level 9 compression brings it down to around 100 kb. It neither has a large impact on the client, nor server application, but significantly reduces internet usage on a large scale.
> 
> In the end, this should also bring you to increasing server-side performance, which might lead you to decreasing the csv export update interval to 10 minutes or even 5 minutes.

**Update:** 
The comparison of file size is not 2Mb vs 100 kb, but instead around 480 kb vs 65 kb. So it is 7 times less using a Zip Archive. The previous comparison happens, if you convert the csv to json format.

**Comment by fiki574** [comment]
This seems like an insignificant improvement at this point, as the auction count lowered by twice as much at this point. 

I might consider implementing this if the current way possibly causes noticeable server-sided performance drops in future.

Closing for now, will be reopening if needed.
