### ISSUE TITLE
Create an API, which tells the date of the latest update to auction data

### ISSUE THREAD

**Issue by NovacX** [fiki574/Skylords-Reborn-API-UI#14]
**Suggestion**
Create an Endpoint like /api/auctions/backendUpdateTime, which returns the latest time of the server side backend cache
Create an Endpoint like /api/auctions/csvUpdateTime, which returns the latest time of the server side csv cache /api/auctions/export

**Reason**
While you currently have to download a page or csv file (or the /api/auctions/count endpoint) to detect changes to the server side auction cache, it would be more efficient to request the latest cache time and compare it to the local cache of applications. Should reduce amount and volume of requests to the server.

**Comment by fiki574** [comment]
Created recently.
