### ISSUE TITLE
Adding Card Type (Fire, Lost Souls, TW, etc.) 

### ISSUE THREAD

**Issue by t1421** [fiki574/Skylords-Reborn-API-UI#2]
At the moment i calculate after the request:

        if(fireOrbs > 0 and frostOrbs = 0 and natureOrbs = 0 and shadowOrbs = 0, 'Fire',
	if(fireOrbs = 0 and frostOrbs > 0 and natureOrbs = 0 and shadowOrbs = 0, 'Frost',	
	if(fireOrbs = 0 and frostOrbs = 0 and natureOrbs > 0 and shadowOrbs = 0, 'Nature',		
	if(fireOrbs = 0 and frostOrbs = 0 and natureOrbs = 0 and shadowOrbs > 0, 'Shadow',			
	if(fireOrbs > 0 and frostOrbs = 0 and natureOrbs > 0 and shadowOrbs = 0, 'Twilight',		
	if(fireOrbs = 0 and frostOrbs > 0 and natureOrbs = 0 and shadowOrbs > 0, 'Lost Soul',			
	if(fireOrbs = 0 and frostOrbs > 0 and natureOrbs > 0 and shadowOrbs = 0, 'Stonekin',				
	if(fireOrbs > 0 and frostOrbs = 0 and natureOrbs = 0 and shadowOrbs > 0, 'Bandid',					
	if(fireOrbs = 0 and frostOrbs = 0 and natureOrbs > 0 and shadowOrbs > 0, 'Amii',	
	'Neutral'))))))))) as cards.Type

**Comment by fiki574** [comment]
Sure, there will be _cardType_ property in the returned JSON that will return these, so you don't have to do it on frontend side.

**Comment by fiki574** [comment]
Done.
