### ISSUE TITLE
Get User stats

### ISSUE THREAD

**Issue by Maxxxel** [fiki574/Skylords-Reborn-API-UI#3]
- PVP Ranks
- PVE Ranks

Other stuff may need a way to auth the user as some dont want to expose their card stats, replay data or other information. As a user suggested on the forums, maybe auth with forum acc somehow.

**Comment by fiki574** [comment]
Any kind of public implementations that require user authentication are, for now, out of the picture.

Could you elaborate more what PVP and PVE _Ranks_ exactly mean? Cause leaderboards' rankings are calculated every 6 hours, and not for every player, but only for the first 200, which the game currently supports. Or, is it the PVP ELO and PVE Experience of a specific player?

**Comment by Maxxxel** [comment]
Yea I'd would be cool to have a history of your played matches/rank. Just like lolstats for league of legends. Just a thought. Also how about most played cards, cards with highest winrate etc. 

I love data 🙈

**Comment by fiki574** [comment]
History of your played matches might come in the future, if we were to make something that would allow and support public player data (with auth tho).

However the other part is most likely possible, will see what can be done about those.

**Comment by Maxxxel** [comment]
Amazing, thanks :)
