### ISSUE TITLE
"auctions" retrieve URL endpoint should be GET not POST

### ISSUE THREAD

**Issue by zerazerg** [fiki574/Skylords-Reborn-API-UI#4]
The endpoint https://github.com/fiki574/Skylords-Reborn-API-UI/tree/master/Auctions#post-apiauctionspagenumber that nowadays is... 
![image](https://user-images.githubusercontent.com/2864357/103148885-d0c7f880-4764-11eb-9f6e-83b727ece1a7.png)

... is missusing the POST verb because POST implies a mutation as stated in...
![image](https://user-images.githubusercontent.com/2864357/103148922-2dc3ae80-4765-11eb-8b81-053fd1c7ae99.png)
(https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST).

I was hoping that the actual...
`POST /api/auctions/:page/:number` + `{"input":"Master archers","min":12,"max":30000}` 
... would become...
**`GET /api/auctions?page=1&resultsPerPage=1&cardName=Master Archers&minBfpPrice=12&maxBfpPrice=30000`**

The main improvements that I find in this system is:

1. Follows REST because you are retrieving and object and the verb is the right one: GET
2. Follows REST because you are querying the _auctions_ resource, not the _number_ resource.
3. Now is super easy to apply caching options as GET because as POST, which is NOT idemponen, if you want to cache it must tune some infrastructure elements or the server itself.
4. The search terms are clearer.

I must highlight that in the way I would change the variable names because is quite confusing what "input" (in the body)... must read the doc to see that "input" is "the card name you want"... "max" is also a input... etc.

Starting part by part, I would:

1. `:page/:number` ==> `page=1&resultsPerPage=1` as query param, the variable "number" make it more semantical as "resultsPerPage". I would make "page" as mandatory but leaving "resultsPerPage" optional with the same default value that gets the BattleForge searcher.
2. `body/input` ==> `cardName` as query param... I have a concern if it works as substring or just a equals... in case it's a substring I would set as "cardNameContains"
3. `body/min` ==> `minBfpPrice` as query param
4. `body/max` ==> `maxBfpPrice` as query param

As I told in the [forum post](https://forum.skylords.eu/index.php?/topic/7150-skylords-reborn-api/&do=findComment&comment=89139) If you agree with the terms and give a feature branch I would do the changes myself.

As a final note, I want to make a fully fledged deck building GUI and I was hioing to use your official APIs. That's the reason I'm opening the issue.

**Comment by fiki574** [comment]
Backend code is not publicly available. I might redo the mentioned API points sometime, but it is definetly not a priority.

**Comment by fiki574** [comment]
Updated and changed recently.
