### ISSUE TITLE
Bulk endpoint for getting all auctions

### ISSUE THREAD

**Issue by laurencee** [fiki574/Skylords-Reborn-API-UI#5]
Heya, I would like to be able to integrate the auctions with google spreadsheets but need a way to bulk get the full list of auctions to do so.

Would you consider adding an endpoint for this? The paged variant is fine for individual auctions but I want to do my own filtering/sorting and search stuff over the fulls set so would prefer not to query for every individual page.

**Comment by fiki574** [comment]
Unfortunately, that is not an option. Opens up possibilities of easily DDoS-ing our API services due to almost always above 7000 entries. Regardless of those being fetched from memory and not database, it is a costly and a heavy request.

**Comment by t1421** [comment]
Hmmm I see your point in the DDoS attack possible. (haven’t that in mind but you are right)

At the moment I perform the “auctions/count” request followed by a loop of “return” / 30
So in case of 7000 actions I would perform another ~235 requests to get all actions in to my frontend.
->Are 235 small requests better than 1 big for the server / API / database / traffic 

I really don’t know and i´m curious

**Comment by fiki574** [comment]
Yes. Many smaller requests are often better than a single big one.

Looping and sending requests like that is completely fine and exactly how I imagined it to work. However, make sure you are not doing that too frequently.

**Comment by t1421** [comment]
THX, will keep that in mind. (ATM i check ~15-30min. )

**Comment by laurencee** [comment]
The fix to the DDoS possibility would be to rate limit the endpoint heavily to like once a minute. The responses could also be cached so it'd only get calculated server side a once or twice a minute.

Doing a quick test locally to see the expected file size, a csv data set of 7k entries using the auctions response as row data ends up with around 400-450KB file that gzipped would be 100-150KB. Json would obviously be bigger but would still compress nicely.

I'll use what's available for now thanks.

**Comment by fiki574** [comment]
Sure, I will add it then.

**Comment by fiki574** [comment]
Done.
