### ISSUE TITLE
Add more auctions search terms

### ISSUE THREAD

**Issue by kYwzor** [fiki574/Skylords-Reborn-API-UI#6]
Currently, you can only search auctions by card name (input), minimum price in BFP (`min`) and maximum price in BFP (`max`). However, I believe there are other useful search terms that could be implemented, which I will list below. As an aside, I understand that all of these operations could be trivially done on the client-side, but I think these additions would make the API much easier to work with.

___

**Improved Price Filtering**

I ran a few tests and it appears that setting `min` and `max` forces `currentPrice`, `startingPrice` and `buyoutPrice` (if not 0) to all stay within those bounds. For example, searching for Shatter Ice currently returns this:

> [{"auctionId":228101,"cardName":"Shatter Ice","cardId":969,"currentPrice":9,"startingPrice":9,"buyoutPrice":10,"endingOn":"<48h"},{"auctionId":228435,"cardName":"Shatter Ice","cardId":969,"currentPrice":9,"startingPrice":9,"buyoutPrice":10,"endingOn":"<48h"},{"auctionId":224540,"cardName":"Shatter Ice","cardId":969,"currentPrice":6,"startingPrice":6,"buyoutPrice":12,"endingOn":"<48h"},{"auctionId":224386,"cardName":"Shatter Ice","cardId":969,"currentPrice":2,"startingPrice":2,"buyoutPrice":0,"endingOn":"<24h"}]

But if we set `max` to 10 we get:

> [{"auctionId":228101,"cardName":"Shatter Ice","cardId":969,"currentPrice":9,"startingPrice":9,"buyoutPrice":10,"endingOn":"<48h"},{"auctionId":228435,"cardName":"Shatter Ice","cardId":969,"currentPrice":9,"startingPrice":9,"buyoutPrice":10,"endingOn":"<48h"},{"auctionId":224386,"cardName":"Shatter Ice","cardId":969,"currentPrice":2,"startingPrice":2,"buyoutPrice":0,"endingOn":"<24h"}]

As you can see, although auction 224540 allows us to bid for less than 10 BFP, it was removed from the list because it has a higher buyout price. At the same time, auction 224386 doesn't even have a buyout price and yet it still gets returned. This seems illogical because having a buyout seems to "penalize" the auction, One obvious use-case that would get affected by this is one in which someone tries to figure out if a certain card is biddable for under a certain amount of BFP, but gets no results simply because the card has a high buyout, even though it met their criteria. A similar effect happens when using `min` for auctions that have a low starting price: although the starting price doesn't really affect the current state of the auction, a card with will still be filtered out based on that.

I believe there are two possible solutions for this. The simplest one would be to change `min` and `max` to simply filter based on `currentPrice`. Given that in buyout-only auctions `currentPrice` is essentially `buyoutPrice - 1` this would allow people to search a price bracket for both bids and buyouts (that is, if someone wants buyout-only auctions they can simply filter out anything where `buyoutPrice` is equal to 0). However, I believe the preferred solution would be to separate the search for each of the three fields, that is, it would be great to have `minCurrent`, `maxCurrent`, `minStarting`, `maxStarting`, `minBuyout `and `maxBuyout`.

___

**Searching by time left**

Currently there is no built-in way to filter the results by time left. I was thinking about building a bot that alerts you to auctions with good bidding price that have a short time left, and for that use-case it would be great to be able reduce the number of requests by only getting auctions in which `endingOn="<2h"`.

___

**Sorting by fields**

This one may be a bit too server-intensive, but I'll still suggest it because it would be great. Ideally we would be able to get responses sorted by any of the 5 fields (`cardName`, `currentPrice`, `startingPrice`, `buyoutPrice `and `endingOn`) in an ascending or descending order. I believe it currently sorts all results by `startingPrice` in a descending order, which is honestly not too useful. One of the most common use-cases is to find the cheapest auction for a certain card, so the number of requests could be reduced significantly by allowing sorting.

**Comment by fiki574** [comment]
Implemented as a part of the new Skylords Reborn API Hub: https://hub.backend.skylords.eu/api/docs/auctions/#/Advanced/get_api_auctions_advanced
