### ISSUE TITLE
Maybe Bulk endpoint for Leaderboards too?

### ISSUE THREAD

**Issue by t1421** [fiki574/Skylords-Reborn-API-UI#7]
I really like the new action-csv API. Makes my code way smoother and the reload of the application faster.

So I was wondering: Is it possible to something similar for the leaderboards?

It’s would be just a nice to have. Actions are currently >15.000, so that’s no comparison to the 200 names for the Leaderboard. (and probably more peoples are interested in the card prices)

**Comment by fiki574** [comment]
I don't see why not. Adding to my TODO list.

**Comment by fiki574** [comment]
Implemented.
