### ISSUE TITLE
Stats - API -> BFP request has decimal value?

### ISSUE THREAD

**Issue by t1421** [fiki574/Skylords-Reborn-API-UI#8]
Im not sure if this is a bug, but when i get the current BFPs (https://stats.backend.skylords.eu/api/bfp)
the return is: {"count":19071220.485697}

How is it possible to have a ~half BFP?
Has it to do with the new reserve mechanic?

**Comment by fiki574** [comment]
Seems so. Better ask Zyna or Lada to be sure, since all I do is execute a query and pass down the results, so if there is a bug, it is not in the API.

**Comment by t1421** [comment]
Update: Ladadoos has confirmed that the decimal is not a but, its part of the boost-, reserve- and reward-system
